version: '3'
services:
  database_server:
    build:
      context: ./database_server/
      args:
        - mysql_password=magento2
        - mysql_database=magento2
    container_name: mysql
    volumes: 
      - ./database_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./database_server/mysql.sh:/etc/mysql.sh
    ports:
      - "3306:3306"
