version: '3'
services:
  web_server:
    build:
      context: ./web_server/
    container_name: web_server
    #environment:
    #  - VIRTUAL_HOST=magento.local
    volumes:
      - ./backend-magento:/var/www/html/backend-magento
      - ./web_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
    #links:
    #  - mysql_db
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: kamioun
      MYSQL_USER: magento2
      MYSQL_PASSWORD: magento2
      MYSQL_ROOT_PASSWORD: magento2
    volumes:
      - ./kamioun.sql:/var/lib/kamioun.sql
      - ./mysql:/var/lib/mysql
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql_db
      UPLOAD_LIMIT: 1024M
    depends_on:
      - mysql_db
    ports:
      - "8080:80"

volumes:
  mysql:
